# Site Settings
# Edit this file to change global site settings

siteName: "Sabras Kitchen"
tagline: "Authentic Kenyan Flavors"
phone: ""
email: ""
address: ""
socialLinks:
  facebook: ""
  instagram: ""
  twitter: ""
  youtube: ""
